# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lanpokn/Documents/2022/slam/ex1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lanpokn/Documents/2022/slam/ex1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lanpokn/Documents/2022/slam/ex1/CMakeFiles /home/lanpokn/Documents/2022/slam/ex1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lanpokn/Documents/2022/slam/ex1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named colorfulPoint

# Build rule for target.
colorfulPoint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colorfulPoint
.PHONY : colorfulPoint

# fast build rule for target.
colorfulPoint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfulPoint.dir/build.make CMakeFiles/colorfulPoint.dir/build
.PHONY : colorfulPoint/fast

#=============================================================================
# Target rules for targets named test_cv

# Build rule for target.
test_cv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cv
.PHONY : test_cv

# fast build rule for target.
test_cv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cv.dir/build.make CMakeFiles/test_cv.dir/build
.PHONY : test_cv/fast

src/colorfulPoint.o: src/colorfulPoint.cpp.o
.PHONY : src/colorfulPoint.o

# target to build an object file
src/colorfulPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfulPoint.dir/build.make CMakeFiles/colorfulPoint.dir/src/colorfulPoint.cpp.o
.PHONY : src/colorfulPoint.cpp.o

src/colorfulPoint.i: src/colorfulPoint.cpp.i
.PHONY : src/colorfulPoint.i

# target to preprocess a source file
src/colorfulPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfulPoint.dir/build.make CMakeFiles/colorfulPoint.dir/src/colorfulPoint.cpp.i
.PHONY : src/colorfulPoint.cpp.i

src/colorfulPoint.s: src/colorfulPoint.cpp.s
.PHONY : src/colorfulPoint.s

# target to generate assembly for a file
src/colorfulPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfulPoint.dir/build.make CMakeFiles/colorfulPoint.dir/src/colorfulPoint.cpp.s
.PHONY : src/colorfulPoint.cpp.s

src/test_cv.o: src/test_cv.cpp.o
.PHONY : src/test_cv.o

# target to build an object file
src/test_cv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cv.dir/build.make CMakeFiles/test_cv.dir/src/test_cv.cpp.o
.PHONY : src/test_cv.cpp.o

src/test_cv.i: src/test_cv.cpp.i
.PHONY : src/test_cv.i

# target to preprocess a source file
src/test_cv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cv.dir/build.make CMakeFiles/test_cv.dir/src/test_cv.cpp.i
.PHONY : src/test_cv.cpp.i

src/test_cv.s: src/test_cv.cpp.s
.PHONY : src/test_cv.s

# target to generate assembly for a file
src/test_cv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cv.dir/build.make CMakeFiles/test_cv.dir/src/test_cv.cpp.s
.PHONY : src/test_cv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... colorfulPoint"
	@echo "... test_cv"
	@echo "... src/colorfulPoint.o"
	@echo "... src/colorfulPoint.i"
	@echo "... src/colorfulPoint.s"
	@echo "... src/test_cv.o"
	@echo "... src/test_cv.i"
	@echo "... src/test_cv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

